# Generated by Django 6.0.5 on 2026-05-16 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('webhook_url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhooks.event')),
            ],
            options={
                'ordering': ['attempted_at'],
            },
        ),
    ]
